/*
 * generated by Xtext
 */
package ai.vital.flora2.edit;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Flora2EditorRuntimeModule extends ai.vital.flora2.edit.AbstractFlora2EditorRuntimeModule {

}
