/*
* generated by Xtext
*/
package ai.vital.flora2.edit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Flora2EditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ai/vital/flora2/edit/parser/antlr/internal/InternalFlora2Editor.tokens");
	}
}
