/*
* generated by Xtext
*/
package ai.vital.flora2.edit.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ai.vital.flora2.edit.services.Flora2EditorGrammarAccess;

public class Flora2EditorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Flora2EditorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WHITESPACE", "RULE_SINGLE_LINE_COMMENT");
	}
	
	@Override
	protected ai.vital.flora2.edit.parser.antlr.internal.InternalFlora2EditorParser createParser(XtextTokenStream stream) {
		return new ai.vital.flora2.edit.parser.antlr.internal.InternalFlora2EditorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public Flora2EditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Flora2EditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
