/**
 * generated by Xtext
 */
package ai.vital.flora2.edit.validation;

import ai.vital.flora2.edit.validation.AbstractFlora2EditorValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class Flora2EditorValidator extends AbstractFlora2EditorValidator {
}
