/**
 * generated by Xtext
 */
package ai.vital.flora2.edit.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class Flora2EditorOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
