/*
 * generated by Xtext
 */
package ai.vital.flora2.edit.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFlora2EditorValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ai.vital.flora2.edit.flora2Editor.Flora2EditorPackage.eINSTANCE);
		return result;
	}
}
