/**
 * generated by Xtext
 */
package ai.vital.flora2.edit.ui.contentassist;

import ai.vital.flora2.edit.ui.contentassist.AbstractFlora2EditorProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class Flora2EditorProposalProvider extends AbstractFlora2EditorProposalProvider {
}
