/**
 * generated by Xtext
 */
package ai.vital.flora2.edit.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class Flora2EditorQuickfixProvider extends DefaultQuickfixProvider {
}
