/*
 * generated by Xtext
 */
package ai.vital.flora2.edit.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ai.vital.flora2.edit.ui.internal.Flora2EditorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Flora2EditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Flora2EditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Flora2EditorActivator.getInstance().getInjector(Flora2EditorActivator.AI_VITAL_FLORA2_EDIT_FLORA2EDITOR);
	}
	
}
